# Generated by Django 4.1.7 on 2023-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default=1, max_length=100000),
            preserve_default=False,
        ),
    ]
